### ISSUE TITLE
problem changing random group parameter values

### ISSUE THREAD

**Issue by bgarwood** [spacetelescope/PyFITS#102] opened 2015-06-08 18:04 UTC
I have a file with a random groups PHDU.  I'd like to change some of the values in that file and have those value stay changed in the file on disk.  But when I attempt it via several different ways, the parameter files remain unchanged on disk.  I can change the data array values (in one group, multiple groups, one or more elements in the array in one group, etc) without any problem.

Is this a bug, feature, or am I just not doing it right.

e.g. one parameter is "RA"

```
f = pyfits.open('myfile.fits',mode='update')
# this gets the entire parameter vector just fine
ra = f[0].data.field('RA') 
ra[0] = 0.5
# This doesn't work
f[0].data.field['RA'] = ra
```

Other things that also don't work:

```
f[0].data[0]['RA'] = 0.5
f[0].data.field('RA')[0] = 0.5
f[0].data.field('RA')[:] = ra
```

All of the above change the value in memory so that f[0].data[0] shows a value of 0.5 after each of those attempts.  But it's never written back to disk.  Explicitly doing f.flush() doesn't help.  Using f.writeto('newfile.fits') also doesn't write out those values to the new file - the values found in the original myfile.fits are just copied over.  Equivalent operations on the data array associated with group 0 all work and change the value on disk without any problem.

Thanks.

**Comment by embray** [comment] 2015-06-08 20:42
Hi, sorry for the confusion.  This sounds like a bug to me.  What version of PyFITS are you using?  This doesn't seem to be an issue in Astropy (although the current version of Astropy also has a bug, astropy/astropy#3730 that is preventing this from working, though with the fix for that bug in place I otherwise can't reproduce the issue on Astropy).

**Comment by embray** [comment] 2015-06-08 20:45
This seems to be working on the current version of PyFITS as well.  But there could be something particular about the file you're trying to update.  Could you please post the header for the primary HDU?  Thanks.

**Comment by bgarwood** [comment] 2015-06-10 16:59
I'm using pyfits 3.2.dev.  I also have a now somewhat old version of astropy (0.4.4) that behaves the same way.

I had worried that this behavior was caused by an attempt to extend an existing random group PHDU (using this file) with pyfits by simply setting GCOUNT to the new count and then referencing the new position, e.g.

    f[0].header['GCOUNT'] = 661   # was 660
    f[0].data[660] = f[0].data[0]       # to put something there
That was when I discovered first of all that the file did in fact get longer and the data array values were copied over, but the parameter values were all zeros and then nothing I could do would change those parameter values.  I tried just replacing parameter values on a virgin copy of that same FITS file and that behaves as described in my original issue text, so the failure is unrelated to my (apparently successful) attempt to extend the size of an existing groups PHDU.

Here's the header (it's ugly, we're trying to replace the legacy c code that created this file):

```
SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                  -32 / number of bits per data pixel                  
NAXIS   =                    6 / number of data axes                            
NAXIS1  =                    0 / length of data axis 1                          
NAXIS2  =                    3 / length of data axis 2                          
NAXIS3  =                    2 / length of data axis 3                          
NAXIS4  =                  201 / length of data axis 4                          
NAXIS5  =                    1 / length of data axis 5                          
NAXIS6  =                    1 / length of data axis 6                          
EXTEND  =                    T / FITS dataset may contain extensions            
GROUPS  =                    T / random group records are present               
PCOUNT  =                    4 / number of random group parameters              
GCOUNT  =                  660 / number of random groups                        
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
BZERO   =                   0. / Zero Level                                     
BSCALE  =                   1. / Scale value                                    
SITELAT =                   0. / GBT location and pointing data                 
SITELONG=                   0. / GBT location and pointing data                 
SITEELEV=                   0. / GBT location and pointing data                 
LPC_AZ1 =                   0. / GBT location and pointing data                 
LPC_AZ2 =                   0. / GBT location and pointing data                 
LPC_EL  =                   0. / GBT location and pointing data                 
ORIGIN  = 'NRAO, Green Bank'   / WV 24944  304-456-2011                         
TELESCOP= '        '           / Robert C. Byrd                                 
BUNIT   = 'Tmb     '           / JY/BEAM or K/BEAM                              
CTYPE2  = 'COMPLEX '           / Signal, Baseline, Weight                       
CRVAL2  =                   1.                                                  
CDELT2  =                   1.                                                  
CRPIX2  =                   1.                                                  
CROTA2  =                   0.                                                  
CTYPE3  = 'STOKES  '           / X, Y or R, L/                                  
CRVAL3  =                  -1.                                                  
CDELT3  =                  -1.                                                  
CRPIX3  =                   1.                                                  
CROTA3  =                   0.                                                  
CTYPE4  = 'FREQ    '           / frequency in LSR frame                         
VELREF  =                    1 / 1 LSR, 2 HEL, 3 OBS, +256 Radio                
RESTFREQ=         23706295000.                                                  
ALTRVAL =                   0.                                                  
ALTRPIX =     143.288427504205                                                  
BANDWIDT=     24413984.9726484                                                  
CRVAL4  =     23740024332.8934                                                  
CDELT4  =     122069.924863242                                                  
CRPIX4  =                419.6                                                  
CROTA4  =                   0.                                                  
CDELT5  =                   1.                                                  
CRPIX5  =                   1.                                                  
CROTA5  =                   0.                                                  
CTYPE5  = 'RA      '           / Right Ascension                                
CTYPE6  = 'DEC     '           / Declination                                    
CROTA6  =                   0.                                                  
CROTA6  =                   0.                                                  
EPOCH   =                2000. / RA Dec reference epoch                         
PTYPE1  = 'RA      '           / RA in Degrees                                  
PSCAL1  =     57.2957795130823 / Unit conversion factor                         
PZERO1  =                   0. / Unit conversion factor                         
PTYPE2  = 'DEC     '           / Declination in Degrees                         
PSCAL2  =     57.2957795130823 / Unit conversion factor                         
PZERO2  =                   0. / Unit zero value                                
PTYPE3  = 'BEAM    '           / point number*256 + Scan                        
PSCAL3  =                   1. / Unit conversion factor                         
PZERO3  =                   0. / Unit zero value                                
PTYPE4  = 'DATE    '           / Date+time in Julian date (days)                
PSCAL4  =                   1. / Unit conversion factor                         
PZERO4  =            2455442.5 / Unit zero value                                
OBJECT  = 'W51     '           / DistantCreation                                
IMCLASS = '23701   '           / Class is Center Freq (MHz)                     
IMNAME  = 'W51     '           / WV 24944  304-456-2011                         
SORTORD = 'TB      '           / Data time sorted for efficiency                
DATE-OBS= '03/09/10'           / UTC Date of observation                        
SCAN    =                   14 / GBT M&C Scan Number                            
OBSERVER= 'Glen Langston'      / Student of the Universe                        
PROJID  = '        '           / Study of the Universe                          
INSTRUME= 'RcvrArray18_26'     / Front End                                      
REFRACT =                   0. / Refraction model (deg)                         
DAZMODEL=                   0. / Azimuth   offset (deg) at reference pos.       
DELMODEL=                   0. / Elevation offset (deg) at reference pos.       
COORDTYP= 'J2000   '           / Coordiante Type                                
CRVAL5  =     290.907755487022 / Right Ascension of Center                      
CRVAL6  =     14.5055737886031 / Declination of Center                          
HISTORY SORTORD = 'TB      ' / Data time sorted                                 
HISTORY AIPS   SORT ORDER = 'TB'                                                
HISTORY UVSRT  SORT = 'TB'   / New sort order                                   
BMAJ    =  0.00868247260359543 / Angular Resolution (FWHM Degrees)              
BMIN    =  0.00868247260359543 / Angular Resolution (FWHM Degrees)              
BPA     =                   0. / Orientatio (Degrees)                           
CELLSIZE=                    6 / Desired Image Cellsize (arcsec)                
CDELT5  =  0.00166666666666667 / Desired Image Cellsize (degree)                
CDELT6  =  0.00166666666666667 / Desired Image Cellsize (degree)                
CRPIX5  =                   84 / Desired Image X Size (pixels)                  
CRPIX6  =                   84 / Desired Image Y Size (pixels)                  
HISTORY RcvrArray18_26  SAMPLER=B3 SIDE=L SIG=T CAL=F                           
HISTORY writeSdfits 4.0      / Glen Langston, NRAO GB  

```

**Comment by embray** [comment] 2015-06-10 17:07
PyFITS is currently on v3.3.x.  I know there have been fixes to random groups in the recent past, so if this was an issue before it could be fixed in a newer version (though I haven't confirmed this).  Thanks for the header, I'll look into if there's anything particular about it.

One thing I note is that the RA, DEC, and DATE parameters are using PSCAL and PZERO which have some known bugs reported in astropy/astropy#2751.  I'm looking into fixing that bug.

**Comment by embray** [comment] 2015-06-10 17:09
Oh, and when using pyfits don't manually set header keywords that relate to the data structure.  For example, don't bother trying to manually update keywords like 'GCOUNT'.  It will write the correct header keywords to represent the *data* attached to an HDU.  No matter what you put in the header by hand it will be overwritten to whatever is needed to accurately represent the data.

**Comment by bgarwood** [comment] 2015-06-10 17:36
Thanks.  Ahhhh.  It's clearly an issue with PSCAL and PZERO.  If I set the BEAM parameter to something else, that does get correctly written to disk and on a reopen in a new python session that change is still there.  And I can't tell if the PSCAL/PZERO issue you linked to is really the same as this one where here the values that are recovered when the file is reopened are always what they where before any attempt was made to modify them in python (i.e. the changed values seem to not be written back to disk at all).  But it seems to at least be related.

**Comment by embray** [comment] 2015-06-10 18:09
Thanks for checking that--the symptom is different I agree, but they're probably related (i.e. flaky support for scaling in random groups).  I'd definitely like to try to get that fixed.  There was some work done recently on improving scaling for table columns, and most of that work should be portable over to random groups as well (since in PyFITS they're just implemented as tables anyways).

**Comment by bgarwood** [comment] 2015-06-10 18:20
That would be good.  The scaling and zero usage here are, I think, to get around the random group feature that the type of all of the data is the same and here the main data array is a 32-bit float.  That's probably not adequate precision for the DATE because of the baggage of expressing is as JD - the PZERO value just subtracts off that extra stuff, and whats left can be stored as a 32-bit float.  The RA,DEC scaling is so that the unscaled values stored are radians but they are in degrees after scaling. I need to think a bit on whether that scaling is necessary to get the precision needed into a 32-bit float.  And we'd use tables, too, if the goal wasn't to get this data into class AIPS using a path in established several decades ago - that's the form the data are in before we squeeze it into this form.

**Comment by bgarwood** [comment] 2015-06-10 18:27
As a workaround, if my python code was writing this PHDU from scratch would it work to initially set PSCALE and PZERO to 1.0 and 0.0 for all parameters first, do the scaling and offset and write the parameter values out the way they should be had those been set as I wanted them to, and then set PSCALE and PZERO keywords to what they should have been?

**Comment by embray** [comment] 2015-06-10 18:33
It might work, but I'm not 100% certain.  For images the way you write scaled data is to use to `.scale()` method: https://pythonhosted.org/pyfits/api_docs/api_images.html#pyfits.CompImageHDU.scale

That is, you assign the data in the appropriate *physical* values, then use the `.scale()` method to specify what scaling you want for the storage.  This feature is missing for random groups HDUs, but could be added.

**Comment by embray** [comment] 2015-06-10 18:39
Okay, I tried out your suggested workaround and it seems to have gone fine--manually scaling the parameter data and setting the 'PSCALn' and 'PZEROn' keywords manually does work in this case (for images it's all managed by the ImageHDU class, but it's not as well supported currently for random groups, though at least you can still manage it manually for now).

**Comment by bgarwood** [comment] 2015-06-10 18:43
Great.  That at least gets me into the experimental stage to see if this can be used to replace the legacy c code (that none of us wrote and is therefore becoming very hard to maintain) we're current using.

**Comment by embray** [comment] 2015-06-10 19:15
Out of curiosity, what legacy C code is that?  Just something in house, or something I might have heard of?

Also, speaking of which, were you aware that PyFITS, as a standalone package, is nearing end of support?  Although there's no official timeline for that, the rate of releases has slowed significantly, and most new development is happening directly in Astropy, where pyfits is available as `astropy.io.fits`.

If your goal is replacing legacy code Astropy is a better choice than PyFITS.  Most existing pyfits code can be used with Astropy just by changing the import statements to `from astropy.io import fits as pyfits`.

**Comment by bgarwood** [comment] 2015-06-10 19:30
In house.  We use it to get GBT data into AIPS to produce images.  We have a newer pure-python gridder that works, but is really sloppy with memory use.  Also AIPS is really fast and that will be hard to beat, so users will continue to want to use AIPS for the foreseeable future (CASA is still quite slow and the single dish imaging support is not quite ready for prime time, and is also a memory hog).  So we go from FITS tables -> FITS random groups -> AIPS pseudo-UV data -> images and this legacy code covers the first step.  That legacy code doesn't use any dynamic memory allocation so there's a structure that holds 32K channels and up to100 K spectra and we regularly exceed that with data from the newest GBT spectrometer.  I'm not sure that pyfits will be much better on memory use, although I'm hoping that by using memmap=True that things will be somewhat better - at least on reading the FITS tables.  It certainly won't be any worse.  The other option is to use fitsio from Eric Sheldon, but there's no working random groups support there just yet - although he seems to be working on it.

And we are moving to astropy, eventually.

**Comment by embray** [comment] 2015-06-10 20:52
Got it, and thanks for the details.  Let me mull over it and get back to you later on some things you might be able to do to speed up that first step.  As already noted elsewhere fitsio is definitely best when it comes to raw I/O of tables, but there are some tricks you can use to speed up pyfits a great deal on that front too.

**Comment by bgarwood** [comment] 2015-08-04 19:48
Just checking in here to see if you had any thoughts on speeding things up.  Also, I discovered an issue today in pyfits 3.3 where writing scalar parameters in a random group seems to sometimes fail (similar scalings, different values, not sure what's happening) and I'm wondering if there's been any other report of that (probably no one else really uses this feature).  I've worked around it by doing the scaling myself, writing out the pre-scaled values, closing and reopening that file and then updating just the PSCAL* and PZERO* keywords as appropriate to describe the scale and offset I did before the values were written.  It's odd, because the original plan (letting pyfits to the scaling etc when writing) worked on one set of param values but didn't on another.  They're RA, DEC,and TIME (degrees, degrees, and Jd) in both cases so, as I said, it's odd it worked in one case and failed in the other.

**Comment by embray** [comment] 2015-08-11 22:12
@bgarwood 
There are two main tricks to speeding things up here.  The first is to make sure the files you're reading from contain data that has already been rescaled.  That is, it does not have non-trivial PSCALn or PZEROn keywords.  For example it should work if you do:

```python
with fits.open('path/to/file.fits') as hdul:
    hdul[0].data  # Access the data so that the scaling is applied to it
    hdul[0].writeto('path/to/output.fits')
```

the data written to disk should have the raw physical values, which is then faster to read in later.

The other trick is that you can get to the raw Numpy array via `hdul[0].data.base`.  This allows much faster access than through the `GroupsData` object that wraps it, which has some known performance defects.  However, you lose support for various FITS-isms (such as scaled data, hence rescaling it first) and have to be more careful.  The raw numpy interface is much faster, especially for reading one row at a time.

**Closed** 2017-12-13 15:59 UTC
Labels: Bug
